### ISSUE TITLE
README / Proposal Updates for milestone 2

### ISSUE THREAD

**Issue by brendoncampbell** [UBC-MDS/DSCI_522-Group-403-Student-Performance#24]
- [x] Save as a .Rmd file to include auto-generated references in .md output?(https://github.com/ttimbers/breast_cancer_predictor/blob/v1.1/README.Rmd)
- [x] Archive current readme as a proposal.md file in the doc directory
- [x] “Introduction” section: Update/consolidate project summary with analysis procedure (see tiffany’s example repos)
- [x] “Usage” section: Explain how to run your data analysis (which order scripts are run in, what expected arguments/inputs are, possible flow chart -bleh). 
- [x] “Dependencies” section (include citations for the packages here so that they appear in the "References" section below?
- [x] “License” section? (https://github.com/ttimbers/breast_cancer_predictor/tree/v1.1) 
- [x] “References” section

**Comment by brendoncampbell** [comment]
Completed with PR #44
